In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
b.shape
b.dtype
b.ndim

[[1 2 3]
 [4 5 6]]


2

In [11]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
c = range(10000)
%timeit [i ** 3 for i in c]

3.46 ms ± 37.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
c_np = np.arange(10000)
%timeit c_np ** 3

19.7 µs ± 279 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]
%timeit list(map(lambda x, y: x*y, l1, l2))

1.21 ms ± 62.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
a1 = np.array(l1)
a2 = np.array(l2)
%timeit a1 * a2

8.71 µs ± 40.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
np.eye(3) # creates an identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.full((3, 3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [22]:
np.full((3, 3), 2.2, dtype=np.int32)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [24]:
v = np.array([1, 2, 3])
np.tile(v, (3, 2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [26]:
a = np.linspace(1, 50, 100)
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [27]:
a.itemsize # memory used to store this

8

In [28]:
np.arange(18).reshape(2, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [34]:
np.random.seed(0)
a = np.random.randn(3, 3)
a
b = a
print(a, b)
b[1, 1] = 89
print(a, b)
# a also changes because both arrays are stored in the same location

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]] [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]
[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932  89.         -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]] [[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932  89.         -0.97727788]
 [ 0.95008842 -0.15135721 -0.10321885]]


In [35]:
np.shares_memory(a, b)

True

In [37]:
#To avoid this
b = a.copy()
np.shares_memory(a, b)

False

In [38]:
a == b # compares elementwise

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [41]:
# to stack two arrays
np.vstack((a, b))
np.hstack((a, b))

array([[ 1.76405235,  0.40015721,  0.97873798,  1.76405235,  0.40015721,
         0.97873798],
       [ 2.2408932 , 89.        , -0.97727788,  2.2408932 , 89.        ,
        -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885,  0.95008842, -0.15135721,
        -0.10321885]])

In [45]:
np.sum([np.sin(a), np.cos(a)])

7.875512335677377

In [46]:
a.std(0)

array([ 0.53292604, 41.89696462,  0.80004221])

In [48]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.linalg.det(a)

0.0

In [52]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [59]:
a = np.array((3, 3), dtype=bool)
a

array([ True,  True])

a.argmax() returns the index of the maximum value

In [62]:
a = np.arange(1, 10) # shape (9, )
a[:, np.newaxis].shape
# np.sort is used for sorting

(9, 1)